#ifndef _HAL_HEAT_COOL_ELEMENTS_CONFIG_H_
#define _HAL_HEAT_COOL_ELEMENTS_CONFIG_H_

#define LED_SYSTEM_PORT 		DIO_U8PORT_B
#define LED_SYSTEM_PIN			DIO_U8PIN0



#endif /* _HAL_HEAT_COOL_ELEMENTS_CONFIG_H_ */
