#include "ERROR_STATE.h"
#include "TYPES.h"
#include "DIO_interface.h"

#include "SEVENSEGMENT_config.h"
#include "SEVENSEGMENT_private.h"

SSG_t SEVENSEGMENT_AstrSevenSegmentConfig [SSG_NUMBER]=
{
		/*FIRST SSG 19 */
		{
			DIO_U8PORT_C, DIO_U8PIN0,
			DIO_U8PORT_C, DIO_U8PIN1,
			DIO_U8PORT_C, DIO_U8PIN2,
			DIO_U8PORT_C, DIO_U8PIN3,
			DIO_U8PORT_C, DIO_U8PIN4,
			DIO_U8PORT_C, DIO_U8PIN5,
			DIO_U8PORT_C, DIO_U8PIN6,
			DIO_U8PORT_B, DIO_U8PIN6, //COMMON PORT & PIN
			NOT_CONNECTED, NOT_CONNECTED,//DOT	PORT & PIN
			COMMON_CATHOND
		},

		/*SECOND SSG*/

		{
			DIO_U8PORT_C, DIO_U8PIN0,
			DIO_U8PORT_C, DIO_U8PIN1,
			DIO_U8PORT_C, DIO_U8PIN2,
			DIO_U8PORT_C, DIO_U8PIN3,
			DIO_U8PORT_C, DIO_U8PIN4,
			DIO_U8PORT_C, DIO_U8PIN5,
			DIO_U8PORT_C, DIO_U8PIN6,
			DIO_U8PORT_B, DIO_U8PIN7, //COMMON PORT & PIN
			NOT_CONNECTED, NOT_CONNECTED,//DOT	PORT & PIN
			COMMON_CATHOND
		}


};

